### PR TITLE
Fixed youtube-dl formatting options

### PR DESCRIPTION
**Pull request by AshbyGeek**
Fixed the format picking mechanism in return_full_url so that youtube-dl's filtering picks the best option and ignores the new youtube DASH format options (which unfortunately means that 1080p youtube videos are out of reach for the moment)

I intend to see if I can use ffmpeg to get 1080p content, but for the moment this is a lot better than it was.

### CODE REVIEW

**Comment by vincelwt** [comment]
Thanks a lot !
Were you able to try it directly on the Pi ? I'm currently don't have a Pi with me to test.

**Comment by AshbyGeek** [comment]
Yeah, but I've only tested youtube so far.

Oh, and you definitely don't need all the separate commits, I believe github has some kind of 'merge-squash' that will squash them all down to a single commit on your repository. I was playing around with different ways of transporting modifications from visual studio on my desktop to my pi.

**Comment by AshbyGeek** [comment]
Ok, it doesn't seem to be working for vimeo, but I think that's more of a general problem with DASH. When I try to play the url we get from youtube-dl with omxplayer it does nothing. When I use the same parameters in plane old youtube-dl it gives a total fragments number and downloads.

I'd like to try a different approach entirely. I think I can just tell youtube-dl to download the file and then use some hooks it provides to have omxplayer start playing before it finishes. That way youtube-dl can deal with all the DASH format problems.

**Comment by vincelwt** [comment]
Didn't Vimeo had format options using single URLs (not dash) ?

**Comment by mheine** [comment]
Is this PR still relevant, or is it something we can close? @AshbyGeek @vincelwt

**Comment by vincelwt** [comment]
I don't think so. I don't see how it improves the projcet at the moment (if Vimeo and all are not working)

**Comment by AshbyGeek** [comment]
Feel free to close it if you want. I haven't touched this stuff in a very long time and I won't have time for quite a while to fix the Vimeo side of things

**Pull request closed without merging**
