### PR TITLE
when extracting youtube url, return best quality possible

### PR DESCRIPTION
**Pull request by fasthall**
'url' tag doesn't work and would throw KeyError.
Iterating through best to worst video quality and return the highest resolution found.
If 1080p is desired, merging DASH video and audio into a single url needs to be implemented.

### CODE REVIEW

**Comment by fasthall** [comment]
If 1080p is desired, merging DASH video and audio into a single url needs to be implemented.

**Comment by vincelwt** [comment]
Hey, thanks for the PR!

It's been a while, since I used youtubedl, I don't remember exactly the properties. 

Doesn't the` video['url'] `property is the maximum quality?

**Comment by fasthall** [comment]
It doesn't have key "url" now. I was using the latest version of youtube-dl and tried it on several youtube videos.
Youtube doesn't provide 1080p single streaming url now. At some point, they separate video and audio source of 1080p videos. For instance, format_id 299 is DASH video and format_id 251 is DASH audio. To play 1080p video you need to play both stream together. Currently the maximum quality we can get via single url is 720p.
I'm not sure if it's related to the issue though, I might be wrong!

**Comment by vincelwt** [comment]
Ok thanks.

Omxplayer doesn't supports stream from differents audio and video url, so I guess for now this is the best possible.

**Pull request merged**
