### PR TITLE
Convert FirefoxExtension to WebExtension

### PR DESCRIPTION
**Pull request by johny-c**
This makes the extension compatible with the new WebExtensions API of Firefox (issue #45). It is just a copy of the ChromeExtension, with two changes in the manifest.json:

- removed "background.persistent" entry
- changed "options_page" entry to "options_ui.page"

For me it runs smoothly in debug mode. I'm not sure if anything else is needed.

### CODE REVIEW

**Comment by Tastyep** [comment]
I've been testing it a bit, I can cast from the menu list using 'send to rpi', but I didn't manage to make it work directly from the player page. I simply clicked the cast page button, but nothing work.
Am I doing smth wrong?

**Comment by johny-c** [comment]
Hi @Tastyep, you were right. The active tab could not be fetched correctly. Should be working now.

**Comment by johny-c** [comment]
That's great. Thanks ;)

**Comment by vincelwt** [comment]
Thanks a lot!! This is awesome :)

**Pull request merged**
